name: Samadhi Factory
favicon: null
layout_spectrum: 0.17348924814723432
typography_spectrum: 0.008777256589382887
title: Happiness productive and sharing smile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#18181a'
    - '#ba2b25'
    - '#4d5353'
    - '#b6b6b6'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
